POST http://127.0.0.1:5000/register
Content-Type: application/json

{
    "username": "user123",
    "password": "pass"
}

###
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "username": "user",
    "password": "pass1"
}

###
GET http://127.0.0.1:5000/users?page=1